name: 'code'

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/code.yaml'
    - 'package.json'
    - 'src/**'
    - 'tests/*'
    - 'tsconfig.json'
    - 'tslint.json'
  pull_request:
    paths:
    - '.github/workflows/code.yaml'
    - 'package.json'
    - 'src/**'
    - 'tests/*'
    - 'tsconfig.json'
    - 'tslint.json'

jobs:
  test:
    name: lint and test
    runs-on: ubuntu-latest
    container: minddocdev/node-alpine-ci:latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@master
    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
    - name: Lint code
      run: yarn lint
    - name: Install helm 3
      run: '
        curl -L https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz | tar xvz &&
        mv linux-amd64/helm /usr/bin/helm &&
        chmod +x /usr/bin/helm &&
        rm -rf linux-amd64 &&
        ls /usr/bin
      '
    - name: Test code
      run: yarn test
